"""initial_schema

Revision ID: 1bcf05100e7e
Revises:
Create Date: 2026-05-15 16:53:32.026492

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1bcf05100e7e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_sources",
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("api_url", sa.Text(), nullable=True),
        sa.Column("license_url", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("source_id", name=op.f("pk_catalog_sources")),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("source_name", sa.String(), nullable=True),
        sa.Column("records_seen", sa.Integer(), nullable=True),
        sa.Column("records_loaded", sa.Integer(), nullable=True),
        sa.Column("errors_count", sa.Integer(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_runs")),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("source_project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("development_status", sa.String(), nullable=True),
        sa.Column("license", sa.String(), nullable=True),
        sa.Column("software_type", sa.String(), nullable=True),
        sa.Column("raw_publiccode_yml", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["catalog_sources.source_id"], name=op.f("fk_projects_source_id_catalog_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("source_id", "source_project_id", name="uq_projects_source_id_source_project_id"),
    )
    op.create_index(op.f("ix_projects_development_status"), "projects", ["development_status"], unique=False)
    op.create_index(op.f("ix_projects_license"), "projects", ["license"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(op.f("ix_projects_source_id"), "projects", ["source_id"], unique=False)
    op.create_table(
        "repositories",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column("repo_name", sa.String(), nullable=True),
        sa.Column("default_branch", sa.String(), nullable=True),
        sa.Column("is_supported", sa.Boolean(), nullable=False),
        sa.Column("last_resolution_status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_repositories_project_id_projects")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
        sa.UniqueConstraint("canonical_url", name=op.f("uq_repositories_canonical_url")),
    )
    op.create_index(op.f("ix_repositories_host"), "repositories", ["host"], unique=False)
    op.create_index(op.f("ix_repositories_project_id"), "repositories", ["project_id"], unique=False)
    op.create_table(
        "project_status_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("repository_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("status_label", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("data_quality_flags", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_project_status_snapshots_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("fk_project_status_snapshots_repository_id_repositories")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["pipeline_runs.id"], name=op.f("fk_project_status_snapshots_run_id_pipeline_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_status_snapshots")),
    )
    op.create_index(
        op.f("ix_project_status_snapshots_observed_at"), "project_status_snapshots", ["observed_at"], unique=False
    )
    op.create_index(
        op.f("ix_project_status_snapshots_project_id"), "project_status_snapshots", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_status_snapshots_repository_id"), "project_status_snapshots", ["repository_id"], unique=False
    )
    op.create_index(op.f("ix_project_status_snapshots_run_id"), "project_status_snapshots", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_project_status_snapshots_status_label"), "project_status_snapshots", ["status_label"], unique=False
    )
    op.create_table(
        "repository_metrics_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("repository_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=True),
        sa.Column("forks", sa.Integer(), nullable=True),
        sa.Column("open_issues", sa.Integer(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("pushed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_commit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_release_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("license_key", sa.String(), nullable=True),
        sa.Column("topics", sa.Text(), nullable=True),
        sa.Column("api_status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_repository_metrics_snapshots_repository_id_repositories"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["pipeline_runs.id"], name=op.f("fk_repository_metrics_snapshots_run_id_pipeline_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository_metrics_snapshots")),
    )
    op.create_index(
        op.f("ix_repository_metrics_snapshots_observed_at"),
        "repository_metrics_snapshots",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repository_metrics_snapshots_repository_id"),
        "repository_metrics_snapshots",
        ["repository_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repository_metrics_snapshots_run_id"), "repository_metrics_snapshots", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repository_metrics_snapshots_run_id"), table_name="repository_metrics_snapshots")
    op.drop_index(op.f("ix_repository_metrics_snapshots_repository_id"), table_name="repository_metrics_snapshots")
    op.drop_index(op.f("ix_repository_metrics_snapshots_observed_at"), table_name="repository_metrics_snapshots")
    op.drop_table("repository_metrics_snapshots")
    op.drop_index(op.f("ix_project_status_snapshots_status_label"), table_name="project_status_snapshots")
    op.drop_index(op.f("ix_project_status_snapshots_run_id"), table_name="project_status_snapshots")
    op.drop_index(op.f("ix_project_status_snapshots_repository_id"), table_name="project_status_snapshots")
    op.drop_index(op.f("ix_project_status_snapshots_project_id"), table_name="project_status_snapshots")
    op.drop_index(op.f("ix_project_status_snapshots_observed_at"), table_name="project_status_snapshots")
    op.drop_table("project_status_snapshots")
    op.drop_index(op.f("ix_repositories_project_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_host"), table_name="repositories")
    op.drop_table("repositories")
    op.drop_index(op.f("ix_projects_source_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_license"), table_name="projects")
    op.drop_index(op.f("ix_projects_development_status"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("pipeline_runs")
    op.drop_table("catalog_sources")
    # ### end Alembic commands ###
